In [1]:
# I want to test other algorithms to. and finding best fitting algorithm for car price prediction
# I am going with multiple linear regression, decision tree, random forest algorithm for same

In [2]:
# importing Libraries

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Importing and reading dataset

ds= pd.read_csv("new_cleaned_data.csv")
ds

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,62,Indigo eCS LS CR4 BS IV,Tata,2017,200000.0,130000,Diesel
1,121,Suzuki Dzire VDI,Maruti,2015,450000.0,104000,Diesel
2,139,Motors Ambassador,Hindustan,2000,70000.0,200000,Diesel
3,183,Indigo eCS LX TDI BS III,Tata,2016,320000.0,175430,Diesel
4,238,Indigo eCS LX TDI BS III,Tata,2016,320000.0,175400,Diesel
5,303,Scorpio VLX Special Edition BS III,Mahindra,2004,230000.0,160000,Diesel
6,313,Scorpio 2.6 CRDe,Mahindra,2007,220000.0,170000,Diesel
7,379,Suzuki Swift Dzire Tour LDi,Maruti,2016,350000.0,166000,Diesel
8,397,Indigo LX TDI BS III,Tata,2016,130000.0,104000,Diesel
9,417,XUV500 W8,Mahindra,2012,560000.0,100000,Diesel
10,426,Suzuki Swift Dzire Tour LDi,Maruti,2015,220000.0,129000,Diesel
11,430,Fortuner 3.0 4x4 MT,Toyota,2010,940000.0,131000,Diesel
12,431,Manza ELAN Quadrajet,Tata,2010,155555.0,111111,Petrol
13,443,Amaze 1.5 E i DTEC,Honda,2016,240000.0,160000,Diesel
14,468,i10 Magna 1.2 Kappa2,Hyundai,2008,275000.0,100200,Petrol
15,469,Corolla H2,Toyota,2003,150000.0,100000,Petrol
16,471,Indigo CS eLS BS IV,Tata,2015,123000.0,100000,Diesel
17,474,Xcent Base 1.1 CRDi,Hyundai,2016,300000.0,140000,Diesel
18,478,Zest XE 75 PS Diesel,Tata,2018,480000.0,103553,Diesel
19,483,Fortuner 3.0 4x2 MT,Toyota,2015,1525000.0,120000,Diesel
20,539,Suzuki Wagon R LXi BS III,Maruti,2003,130000.0,133000,Petrol
21,552,Fluidic Verna 1.6 CRDi SX,Hyundai,2013,350000.0,117000,Diesel
22,553,Indica V2 DLG,Tata,2005,35000.0,150000,Diesel
23,566,Motors One SUV,Force,2013,550000.0,140000,Diesel
24,587,Indigo CS eLX BS IV,Tata,2016,150000.0,104000,Diesel
25,589,Indigo eCS LX TDI BS III,Tata,2014,95000.0,195000,Diesel
26,590,Indigo LX TDI BS III,Tata,2016,230000.0,104000,Diesel
27,591,Indigo eCS LX CR4 BS IV,Tata,2016,230000.0,104000,Diesel
28,612,Manza Aqua Quadrajet,Tata,2014,160000.0,200000,Diesel
29,621,Suzuki Omni LPG BS IV,Maruti,2012,120000.0,160000,LPG
30,636,Innova 2.5 V 7 STR,Toyota,2011,750000.0,147000,Diesel
31,680,Zest XE 75 PS Diesel,Tata,2018,450000.0,102563,Diesel
32,683,Sumo Gold LX BS IV,Tata,2014,275000.0,116000,Diesel
33,690,Suzuki Ertiga Vxi,Maruti,2012,1000000.0,200000,Diesel
34,708,Suzuki Zen LX BSII,Maruti,2004,70000.0,100000,Petrol
35,737,Suzuki Swift Dzire Tour LDi,Maruti,2014,260000.0,120000,Diesel
36,790,Indigo eCS,Tata,2016,130000.0,150000,Diesel
37,804,Sumo Gold FX BSIII,Tata,2013,215000.0,100000,Petrol
38,858,Manza,Tata,2015,100000.0,100000,Diesel
39,862,Qualis,Toyota,2003,180000.0,100000,Diesel
40,863,Santro Xing,Hyundai,2004,45000.0,137495,Petrol
41,866,Zest XE 75 PS Diesel,Tata,2017,290000.0,120000,Diesel
42,868,Indigo eCS LX CR4 BS IV,Tata,2016,160000.0,104000,Diesel
43,869,Suzuki Swift Dzire,Maruti,2016,350000.0,146000,Diesel
44,872,Tavera Neo,Chevrolet,2007,465000.0,100800,Diesel
45,873,Suzuki Dzire,Maruti,2016,325000.0,150000,Diesel
46,886,Corolla Altis,Toyota,2009,300000.0,132000,Petrol

In [4]:
X=ds[['company','name','year','kms_driven','fuel_type']]
y=ds[['Price']]

In [5]:
# Implementing OneHotcoder

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
ohe=OneHotEncoder()
ohe.fit(X[["company","name","fuel_type"]])

OneHotEncoder()

In [6]:
ct=make_column_transformer((OneHotEncoder(handle_unknown = 'ignore',categories=ohe.categories_), ["company","name","fuel_type"]),remainder='passthrough',force_int_remainder_cols=False, sparse_threshold = 0)
ct

ColumnTransformer(force_int_remainder_cols=False, remainder='passthrough',
                  sparse_threshold=0,
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['Chevrolet', 'Force', 'Hindustan', 'Honda', 'Hyundai', 'Mahindra',
       'Maruti', 'Tata', 'Toyota'], dtype=object),
                                                           array(['Amaze 1.5 E i DTEC', 'Corolla Altis', 'Corolla H2',
       'Fluidic Verna 1.6 CRDi SX', 'Fortuner 3.0 4x2 MT'...
       'Sumo Gold FX BSIII', 'Sumo Gold LX BS IV', 'Suzuki Dzire',
       'Suzuki Dzire VDI', 'Suzuki Ertiga Vxi', 'Suzuki Omni LPG BS IV',
       'Suzuki Swift Dzire', 'Suzuki Swift Dzire Tour LDi',
       'Suzuki Wagon R LXi BS III', 'Suzuki Zen LX BSII', 'Tavera Neo',
       'XUV500 W8', 'Xcent Base 1.1 CRDi', 'Zest XE 75 PS Diesel',
       'i10 Magna 1.2 Kappa2'], dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                               handle_unknown='ignore'),
                                 ['company', 'name', 'fuel_type'])])

In [7]:
# making pipeline

from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

reg=LinearRegression()
regDec = DecisionTreeRegressor(random_state = 0)
regRFR = RandomForestRegressor(n_estimators =10, random_state= 0)

pipeLinear = make_pipeline(ct, reg)
pipeDec = make_pipeline(ct, regDec)
pipeRFR = make_pipeline(ct, regRFR)

scores = []
for i in range(0,101):
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.10,random_state=i)
    pipeLinear.fit(X_train,y_train)
    pipeDec.fit(X_train,y_train)
    pipeRFR.fit(X_train,y_train)

    result = pipeLinear.predict(X_test)
    scoreLinear = r2_score(y_test, result)
    rmseLinear = np.sqrt(mean_squared_error(y_test, result))
    
    result = pipeDec.predict(X_test)
    scoreDec = r2_score(y_test, result)
    rmseDec = np.sqrt(mean_squared_error(y_test, result))

    result = pipeRFR.predict(X_test)
    scoreRFR = r2_score(y_test, result)
    rmseRFR = np.sqrt(mean_squared_error(y_test, result))
    
    
    scores.append(('Linear',i, scoreLinear,rmseLinear))
    scores.append(('Decision',i, scoreDec, rmseDec ))
    scores.append(('Random Forest',i, scoreRFR, rmseRFR ))

In [8]:
# Finding best r2 score and RMSE score

scoreDF = pd.DataFrame(data = scores, columns = ["algo", "Iteration", "R2 score", "RMSE Score"])
resultDF = scoreDF.sort_values(by="R2 score", ascending = False)
resultDF
# r2 score must be maximum and RMSE score must be minimum

              algo  Iteration   R2 score     RMSE Score
171         Linear         57   0.802442  242056.166489
207         Linear         69   0.793750  238410.542505
175       Decision         58   0.786833   85732.140997
90          Linear         30   0.770196  257455.318250
197  Random Forest         65   0.750367   46226.322522
..             ...        ...        ...            ...
141         Linear         47 -45.883480  420640.288755
177         Linear         59 -69.890130  465446.278109
294         Linear         98 -77.978558  263306.219454
33          Linear         11 -88.358654  752446.963560
3           Linear          1 -94.465354  781895.214025

[303 rows x 4 columns]

In [9]:
 # Making Pipeline for best suited algorithm(Decision tree) 

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.10,random_state=79)
pipeDec.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough', sparse_threshold=0,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Chevrolet', 'Force', 'Hindustan', 'Honda', 'Hyundai', 'Mahindra',
       'Maruti', 'Tata', 'Toyota'], dtype=object),
                                                                            array(['Amaze 1.5 E i DTEC', 'Corolla Altis', 'Corolla H2',
       'Flui...
       'Suzuki Swift Dzire', 'Suzuki Swift Dzire Tour LDi',
       'Suzuki Wagon R LXi BS III', 'Suzuki Zen LX BSII', 'Tavera Neo',
       'XUV500 W8', 'Xcent Base 1.1 CRDi', 'Zest XE 75 PS Diesel',
       'i10 Magna 1.2 Kappa2'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                handle_unknown='ignore'),
                                                  ['company', 'name',
                                                   'fuel_type'])])),
                ('decisiontreeregressor',
                 DecisionTreeRegressor(random_state=0))])

In [10]:
# predict for my_input

company=input("enter company name : ")
name=input("enter car name : ")
year=int(input("enter year : "))
kms_driven=int(input("enter kms driven : "))
fuel_type=input("enter fuel type : ")
columns=["company","name","year","kms_driven","fuel_type"]
myinput=pd.DataFrame(columns=columns,data=[[company,name,year,kms_driven,fuel_type]])
result=pipeDec.predict(myinput)
print("You should buy it for ~ price : ",result)

enter company name :  Maruti
enter car name :  Suzuki Swift Dzire Tour LDi
enter year :  2003
enter kms driven :  100000
enter fuel type :  Diesel

You should buy it for ~ price :  [70000.]

In [11]:
# Importing to pkl

import pickle as pkl
pkl.dump(pipeRFR, open("CarProjectUsing_other_algos.pkl","wb"))